spring:
  config:
    import:
      - optional:file:env/dev-db.env[.properties]

logging:
  level:
    com.jootalkpia.stock_server: debug
    org.springframework.web.servlet : debug

feign:
  base-url: https://openapivts.koreainvestment.com:29443
  appkey: ${STOCK_APP_KEY}
  appsecret: ${STOCK_APP_SECRET}
  stock-token:
    path: /oauth2/tokenP
    grant-type: client_credentials
  minute-price:
    path: /uapi/domestic-stock/v1/quotations/inquire-time-itemchartprice
    tr-id: FHKST03010200
    custtype : P
    etc-cls-code : ""
    market-div-code : "J"
    pw-data-incu-yn: "N"
