spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      acks: all # 멱등성 프로듀서를 위해 all로 설정, 0 또는 1이면 enable.idempotence=true 불가
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: ${KAFKA_SERVER}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

logging:
  level:
    com.jootalkpia.chat_server: DEBUG  # 또는 INFO

topic:
  minute: jootalkpia.stock.prd.minute
  chat: jootalkpia.chat.prd.message

group:
  minute: minute-price-save-consumer-group
  chat: chat-message-handle-consumer-group-${SERVER_PORT}

server:
 port: ${SERVER_PORT}
