server:
  port : ${GATEWAY_PORT}

auth_server:
  path: http://${EC2_PRIVATE_IP}:${AUTH_PORT}

spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      default-filters:
        - JwtAuthenticationFilter
        - PassportAuthorizationFilter
        - PassportRelayFilter

      routes:
        - id: auth
          uri: http://${EC2_PRIVATE_IP}:${AUTH_PORT}
          predicates:
            - Path=/api/v1/auth/**

        - id: user
          uri: http://${EC2_PRIVATE_IP}:${AUTH_PORT}
          predicates:
            - Path=/api/v1/user/**

        - id: stock
          uri: http://${EC2_PRIVATE_IP}:${STOCK_PORT}
          predicates:
            - Path=/api/v1/stock/**

        - id: file
          uri: http://${EC2_PRIVATE_IP}:${FILE_PORT}
          predicates:
            - Path=/api/v1/files/**

        - id: history
          uri: http://${EC2_PRIVATE_IP}:${HISTORY_PORT}
          predicates:
            - Path=/api/v1/history/**

        - id: workspace
          uri: http://${EC2_PRIVATE_IP}:${WORKSPACE_PORT}
          predicates:
            - Path=/api/v1/workspace/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
