server:
  port : ${GATEWAY_PORT}

spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      default-filters:
        - StripPrefix=2

      routes:
        - id: auth
          uri: http://localhost:${AUTH_PORT}
          predicates:
            - Path= /auth/**

        - id: user
          uri: http://localhost:${AUTH_PORT}
          predicates:
            - Path= /user/**

#        - id: stock
#          uri: http://localhost:${STOCK_PORT}
#          predicates:
#            - Path= /stock/**
#
#        - id: file
#          uri: http://localhost:${FILE_PORT}
#          predicates:
#            - Path= /file/**
#
#        - id: chat1
#          uri: http://localhost:${CHAT_PORT1}
#          predicates:
#            - Path=
#
#        - id: chat2
#          uri: http://localhost:${CHAT_PORT2}
#          predicates:
#            - Path=
#
#        - id: history
#          uri: http://localhost:${HISTORY_PORT}
#          predicates:
#            - Path= /history/**
#
#        - id: workspace
#          uri: http://localhost:${WORKSPACE_PORT}
#          predicates:
#            - Path= /workspace/**
