server:
  port : ${GATEWAY_PORT}

auth_server:
  path: http://${EC2_PRIVATE_IP}:${AUTH_PORT}

spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      default-filters:
        - JwtAuthenticationFilter
        - PassportAuthorizationFilter
        - PassportRelayFilter

      routes:
        - id: auth
          uri: http://${EC2_PRIVATE_IP}:${AUTH_PORT}
          predicates:
            - Path=/api/v1/auth/**

        - id: user
          uri: http://${EC2_PRIVATE_IP}:${AUTH_PORT}
          predicates:
            - Path=/api/v1/user/**

        - id: stock
          uri: http://${EC2_PRIVATE_IP}:${STOCK_PORT}
          predicates:
            - Path=/api/v1/stock/**

        - id: file
          uri: http://${EC2_PRIVATE_IP}:${FILE_PORT}
          predicates:
            - Path=/api/v1/files/**
#
#        - id: chat1
#          uri: http://localhost:${CHAT_PORT1}
#          predicates:
#            - Path=
#
#        - id: chat2
#          uri: http://localhost:${CHAT_PORT2}
#          predicates:
#            - Path=
#
#        - id: history
#          uri: http://localhost:${HISTORY_PORT}
#          predicates:
#            - Path=/history/**
#
#        - id: workspace
#          uri: http://localhost:${WORKSPACE_PORT}
#          predicates:
#            - Path=/workspace/**
