server:
  port: ${SIGNALING_PORT}

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  websocket:
    stomp:
      endpoint: /ws   # ✅ STOMP 엔드포인트가 "/ws"로 설정되어 있어야 함
  messaging:
    broker:
      enabled: true
      destinationPrefixes: /topic, /queue

kurento:
  ws:
    url: "ws://${HOST}:8888/kurento"
