server:
  port: ${SIGNALING_PORT}

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
#      database: ${SIGNALING_REDIS}

kurento:
  ws:
    url: "ws://${HOST}:8888/kurento"
