server:
  port: 8080

spring:
  application:
    name: file_server
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:jootalkpia_file}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: TRACE

  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}
      region:
        static: ${AWS_REGION}
      stack:
        auto: false


