name: BACKEND-CICD

on:
  push:
    branches:
      - dev
    paths:
      - 'src/backend/**' 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - stock_server
          - auth_server
          - workspace_server
          - chat_server
          - file_server
          - history_server
          - push_server
          - state_server

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Java 17(Zulu) 환경 설정
      - name: Set up JDK 17 (Zulu)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
        continue-on-error: true

      # 3. Gradle 빌드
      - name: Build Gradle project
        working-directory: backend/${{ matrix.service }}
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      # 4. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        working-directory: backend/${{ matrix.service }}
        run: |
          docker build --platform linux/amd64 \
            --build-arg JAR_FILE=build/libs/${{ matrix.service }}-0.0.1-SNAPSHOT.jar \
            -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest .

          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest
