name: CI Pipeline for Jutalkpia

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Java 17 환경 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Gradle 빌드
      # 3.1. chat-service 빌드
      - name: Build chat-service
        working-directory: src/backend/chat-service
        run: ./gradlew clean build -x test

      # 4. Docker 이미지 빌드 및 푸시
      # 4.1. chat-service 이미지 빌드 및 푸시
      - name: Build and push Docker image for chat-service
        working-directory: src/backend/chat-service
        run: |
          docker build -t mirlee/chat-service:latest .
          docker push mirlee/chat-service:latest
