# name: BACKEND-CI

# on:
#   push:
#     branches:
#       - dev
#     paths:
#       - 'src/backend/**'

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         service:
#           - auth_server
#           - stock_server
#           - workspace_server

#     steps:
#       # 1. 코드 체크아웃
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # 2. Java 17(Zulu) 환경 설정
#       - name: Set up JDK 17 (Zulu)
#         uses: actions/setup-java@v3
#         with:
#           distribution: 'zulu'
#           java-version: '17'

#       # 3. Gradle 빌드
#       - name: Build Gradle project
#         working-directory: src/backend/${{ matrix.service }}
#         run: ./gradlew clean build -x test

#       # 4. Docker Hub 로그인
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       # 5. Docker 이미지 빌드 및 푸시
#       - name: Build and push Docker image
#         working-directory: src/backend/${{ matrix.service }}
#         run: |
#           docker build -t mirlee/${{ matrix.service }}:latest .
#           docker push mirlee/${{ matrix.service }}:latest

