name: Build and Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev
      - main

  push:
    branches:
      - fe-ci/cicd

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'

      - name: Install pnpm
        run: npm install -g pnpm

      - uses: actions/cache@v4
        id: cache
        with:
          path: |
            node_modules
            .pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          cd src/frontend
          pnpm install --legacy-peer-deps --frozen-lockfile --prod 
          pnpm add turbo --save-dev -w

      - name: Lint code
        run: |
          cd src/frontend
          pnpm lint

      - name: Build project
        run: |
          cd src/frontend
          pnpm build

      - name: Build Storybook
        run: |
          cd src/frontend
          pnpm build-storybook
