name: PR Build Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev
      - main

  push:
    branches:
      - fe-ci/cicd

jobs:
  pr-push-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'

      - name: Install pnpm
        run: npm install -g pnpm

      - uses: actions/cache@v4
        id: cache
        with:
          path: |
            node_modules
            .pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          cd src/frontend
          pnpm install --frozen-lockfile --prod
          pnpm add turbo --save-dev -w

      - name: Lint code
        run: |
          cd src/frontend 
          pnpm lint

      - name: Build project
        run: |
          cd src/frontend
          pnpm build

      - name: Build Storybook
        run: |
          cd src/frontend
          pnpm build-storybook
