name: FRONTEND-CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev
      - main
    paths:
      - 'src/frontend/**'
  push:
    branches:
      - fe-refac/fe-ci

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    if: ${{ github.actor != 'l10nbot' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'src/frontend/pnpm-lock.yaml'

      - name: Ensure Directories Exist
        run: |
          mkdir -p ~/.pnpm-store
          mkdir -p src/frontend/packages/ui/.turbo
          mkdir -p src/frontend/apps/web/.turbo

      - name: Restore pnpm store cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('src/frontend/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Restore Web .turbo Cache
        uses: actions/cache@v4
        with:
          path: src/frontend/apps/web/.turbo
          key: ${{ runner.os }}-turbo-web-${{ hashFiles('src/frontend/apps/web/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-turbo-web-

      - name: Restore UI .turbo Cache
        uses: actions/cache@v4
        with:
          path: src/frontend/packages/ui/.turbo
          key: ${{ runner.os }}-turbo-ui-${{ hashFiles('src/frontend/packages/ui/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-turbo-ui-

      - name: Install dependencies and run CI
        working-directory: src/frontend
        run: |
          pnpm install --frozen-lockfile --prefer-offline
          pnpm turbo lint build --parallel --concurrency=18
