name: FRONTEND-CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev
      - main
    paths:
      - 'src/frontend/**'
      - './fe-ci.yml'
  push:
    branches:
      - fe-test/ci-test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    if: ${{ github.actor != 'l10nbot' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TZ: Asia/Seoul
      TURBO_CACHE_DIR: ./src/frontend/.turbo # Turbo 캐시 디렉토리 설정
    strategy:
      matrix:
        task: [lint, test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'src/frontend/pnpm-lock.yaml'
      - name: Restore pnpm store cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('src/frontend/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-
      - name: Restore Turbo cache for web
        uses: actions/cache@v4
        with:
          path: src/frontend/apps/web/.turbo
          key: ${{ runner.os }}-turbo-web-${{ hashFiles('src/frontend/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-turbo-web-
      - name: Restore Turbo cache for ui
        uses: actions/cache@v4
        with:
          path: src/frontend/packages/ui/.turbo
          key: ${{ runner.os }}-turbo-ui-${{ hashFiles('src/frontend/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-turbo-ui-
      - name: Install Dependencies
        working-directory: src/frontend
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Run Task with Cache
        working-directory: src/frontend
        run: |
          if [ "${{ matrix.task }}" = "lint" ]; then
            pnpm turbo lint --filter=web --filter=@workspace/ui --parallel --cache-dir=.turbo
          elif [ "${{ matrix.task }}" = "test" ]; then
            pnpm turbo test --filter=web --parallel --cache-dir=.turbo
          fi
      - name: Save Turbo cache
        if: always()
        uses: actions/cache@v4
        with:
          path: src/frontend/.turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}

  build:
    if: ${{ github.actor != 'l10nbot' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TZ: Asia/Seoul
      TURBO_CACHE_DIR: ./src/frontend/.turbo
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'src/frontend/pnpm-lock.yaml'
      - name: Restore pnpm store cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('src/frontend/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-
      - name: Restore Turbo cache
        uses: actions/cache@v4
        with:
          path: src/frontend/.turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: ${{ runner.os }}-turbo-
      - name: Install Dependencies
        working-directory: src/frontend
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Run Build with Cache
        working-directory: src/frontend
        run: pnpm turbo build --filter=web --parallel --cache-dir=.turbo
      - name: Save Turbo cache
        if: always()
        uses: actions/cache@v4
        with:
          path: src/frontend/.turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
