name: FRONTEND-CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev
      - main
    paths:
      - 'src/frontend/**'
  push:
    branches:
      - fe-refac/more-ci

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  workspace-ui:
    if: ${{ github.actor != 'l10nbot' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TZ: Asia/Seoul
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'src/frontend/pnpm-lock.yaml'
      - name: Install Dependencies
        working-directory: src/frontend
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Run Lint
        working-directory: src/frontend
        run: pnpm turbo lint --filter=@workspace/ui --parallel

  web:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TZ: Asia/Seoul
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'src/frontend/pnpm-lock.yaml'
      - name: Install Dependencies
        working-directory: src/frontend
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Run Build
        working-directory: src/frontend
        run: pnpm turbo build test lint --filter=web --parallel
