name: FRONTEND-CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev
      - main
    paths:
      - 'src/frontend/**'
  push:
    branches:
      - fe-refac/more-ci

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      artifactName: ${{ steps.upload_artifact.outputs.artifactName }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'src/frontend/pnpm-lock.yaml'

      - name: Install Dependencies
        working-directory: src/frontend
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Upload Node Modules Artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: src/frontend/node_modules

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Download Node Modules Artifact
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: src/frontend
      - name: Run Lint
        working-directory: src/frontend
        run: pnpm turbo lint --filter=web --filter=@workspace/ui --parallel

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Download Node Modules Artifact
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: src/frontend
      - name: Run Build
        working-directory: src/frontend
        run: pnpm turbo build --filter=web --parallel

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Download Node Modules Artifact
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: src/frontend
      - name: Run Tests
        working-directory: src/frontend
        run: pnpm turbo test --filter=web --parallel
