name: FRONTEND-CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev
      - main
    paths:
      - 'src/frontend/**'
      - './fe-ci.yml'
  push:
    branches:
      - fe-fix/ci-bug

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    if: ${{ github.actor != 'l10nbot' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TZ: Asia/Seoul
      TURBO_CACHE_DIR: src/frontend/.turbo
    strategy:
      matrix:
        task: [lint, test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'src/frontend/pnpm-lock.yaml'

      - name: Restore pnpm store cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('src/frontend/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Restore Turbo cache
        id: restore_turbo_build_cache
        uses: actions/cache@v4
        with:
          path: src/frontend/.turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('src/frontend/.turbo') }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install Dependencies
        working-directory: src/frontend
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Run Task with Cache
        working-directory: src/frontend
        run: |
          if [ "${{ matrix.task }}" = "lint" ]; then
            pnpm turbo lint --parallel --cache-dir=.turbo
          elif [ "${{ matrix.task }}" = "test" ]; then
            pnpm turbo test --filter=web --parallel --cache-dir=.turbo
          fi

  build:
    if: ${{ github.actor != 'l10nbot' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TZ: Asia/Seoul
      TURBO_CACHE_DIR: src/frontend/.turbo
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'src/frontend/pnpm-lock.yaml'

      - name: Restore pnpm store cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('src/frontend/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Restore Turbo cache
        id: restore_turbo_build_cache
        uses: actions/cache@v4
        with:
          path: src/frontend/.turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('src/frontend/.turbo') }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install Dependencies
        working-directory: src/frontend
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Run Build with Cache
        working-directory: src/frontend
        run: pnpm turbo build --parallel --cache-dir=.turbo

      - name: Save Turbo cache
        uses: actions/cache@v4
        with:
          path: src/frontend/.turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('src/frontend/.turbo') }}

      - name: Save pnpm store cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('src/frontend/pnpm-lock.yaml') }}
