name: FRONTEND-CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev
      - main
    paths:
      - 'src/frontend/**'
  push:
    branches:
      - fe-refac/fe-ci

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    if: ${{ github.actor != 'l10nbot' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'src/frontend/pnpm-lock.yaml'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.12.3

      - name: Restore Turbo Cache
        uses: actions/cache@v4
        with:
          path: |
            src/frontend/.turbo
            src/frontend/*/.turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        working-directory: src/frontend
        run: |
          # 변경된 패키지만 설치
          pnpm install --frozen-lockfile --prefer-offline --filter="...[origin/main]"

      - name: Cache installed dependencies
        uses: actions/cache@v4
        with:
          path: src/frontend/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('src/frontend/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

  lint:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'src/frontend/pnpm-lock.yaml'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.12.3

      - name: Restore installed dependencies
        uses: actions/cache@v4
        with:
          path: src/frontend/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('src/frontend/pnpm-lock.yaml') }}

      - name: Restore Turbo Cache
        uses: actions/cache@v4
        with:
          path: |
            src/frontend/.turbo
            src/frontend/*/.turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Run Lint
        working-directory: src/frontend
        run: |
          pnpm turbo lint --filter="...[origin/main]" --parallel --concurrency=10

  build:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'src/frontend/pnpm-lock.yaml'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.12.3

      - name: Restore installed dependencies
        uses: actions/cache@v4
        with:
          path: src/frontend/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('src/frontend/pnpm-lock.yaml') }}

      - name: Restore Turbo Cache
        uses: actions/cache@v4
        with:
          path: |
            src/frontend/.turbo
            src/frontend/*/.turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Run Build
        working-directory: src/frontend
        run: |
          pnpm turbo build --filter="...[origin/main]" --parallel --concurrency=10
