name: FRONTEND-CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev
      - main
    paths:
      - 'src/frontend/**'
  push:
    branches:
      - fe-refac/fe-ci

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    if: ${{ github.actor != 'l10nbot' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'src/frontend/pnpm-lock.yaml'

      - name: Install, Lint, and Build
        working-directory: src/frontend
        run: |
          pnpm install --frozen-lockfile --prefer-offline
          pnpm turbo lint --filter=web --filter=@workspace/ui --parallel 
          pnpm turbo build --filter=web --parallel

      # 디버깅: 빌드 산출물 디렉터리 확인 (예: Next.js 빌드 결과물)
      - name: 'Debug: List apps/web directory'
        working-directory: src/frontend/apps/web
        run: ls -la

      - name: 'Debug: List .next directory (build outputs)'
        working-directory: src/frontend/apps/web
        run: |
          if [ -d ".next" ]; then
            echo ".next directory exists:";
            ls -la .next
          else
            echo ".next directory not found";
          fi

      # 디버깅: 워크스페이스 UI 폴더 내용 확인
      - name: 'Debug: List packages/ui directory'
        working-directory: src/frontend/packages/ui
        run: ls -la
