name: Save Cache on PR Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - dev
  push:
    branches:
      - fe-fix/ci-bug

jobs:
  save-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: 'src/frontend/pnpm-lock.yaml'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Install dependencies
        working-directory: src/frontend
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build for updating .turbo cache
        working-directory: src/frontend
        run: pnpm turbo build --filter=web --filter=@workspace/ui --parallel

      - name: Ensure caching directories exist
        run: |
          mkdir -p ~/.pnpm-store
          mkdir -p src/frontend/.turbo

      - name: Save pnpm store cache
        if: always()
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('src/frontend/pnpm-lock.yaml') }}

      - name: Save Turborepo main cache
        if: always()
        uses: actions/cache@v4
        with:
          path: src/frontend/.turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('src/frontend/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ hashFiles('src/frontend/pnpm-lock.yaml') }}-
            ${{ runner.os }}-turbo-
