name: Save Cache on PR Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - dev
  push:
    branches:
      - fe-test/ci-test

jobs:
  save-cache:
    # if: github.event.pull_request.merged == true # 머지된 PR만 실행
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
      - name: Install dependencies
        working-directory: src/frontend
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Build for updating .turbo cache
        working-directory: src/frontend
        run: pnpm turbo build --filter=web --parallel --cache-dir=.turbo
      - name: Ensure caching directories exist
        run: |
          mkdir -p ~/.pnpm-store
          mkdir -p src/frontend/apps/web/.turbo
          mkdir -p src/frontend/packages/ui/.turbo
      - name: Save pnpm store cache
        if: always()
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('src/frontend/pnpm-lock.yaml') }}
      - name: Save Turborepo cache for web app
        if: always()
        uses: actions/cache@v4
        with:
          path: src/frontend/apps/web/.turbo
          key: ${{ runner.os }}-turbo-web-${{ hashFiles('src/frontend/pnpm-lock.yaml') }}
      - name: Save Turborepo cache for ui package
        if: always()
        uses: actions/cache@v4
        with:
          path: src/frontend/packages/ui/.turbo
          key: ${{ runner.os }}-turbo-ui-${{ hashFiles('src/frontend/pnpm-lock.yaml') }}
